DCLite.register("P2-S13-Ask", "\n\n<dc-import name=\"TplF\" page=\"{{page}}\" hint-size=\"100%,1580px\"></dc-import>\n", function (DCLogic) {

class Component extends DCLogic {
  renderVals() {
    return { page: {"lens":"Entity","role":"Entity Executive · Entity A1","scope":"Entity A1 (own entity)","rid":"S-13","nav":"AI Insights","title":"Ask Control Tower","q":"Ask a question of governed data within my scope","trust":"Answers use only data in your scope; restricted items are never confirmed","meta":{"type":"kv","title":"Your question","rows":[["Question","Why is the Entity A1 P07 forecast down, and is any other entity affected?"],["Scope applied","Entity A1 only (your entitlement)"],["Answered by","Explanation Assistant · AI-generated · D0 06:45"]]},"body":[{"type":"text","title":"Answer · separated by provenance","paras":[{"tag":"CERT","t":"Entity A1 P06 production was 100.4% of plan.","src":"OPS-001","h":"P2-S03e-KPIDetail.dc.html"},{"tag":"PRELIM","t":"RM-1 cover is 3.5 days against a 9-day lead time.","src":"SIG-009","h":"P2-E04-Supply.dc.html"},{"tag":"FCST","t":"The P07 forecast is 91.0% of plan because of a −18.4 kt shortfall from D+4.","src":"PRD-001","h":"P2-S12e-Signals.dc.html"},{"tag":"AI · NOT APPROVED","t":"Interpretation: the forecast fall is driven by the RM-1 supply delay, not by reliability or demand."},{"tag":"RESTRICTED","t":"I can only answer for Entity A1. Questions about other entities are outside your scope; I cannot confirm or deny anything about them (GR-09)."}]},{"type":"table","title":"Saved inquiries","cols":["Question","Asked","Status"],"rows":[["Why is the Entity A1 P07 forecast down?","D0 06:45","Answered"],["What is our upstream obligation this month?","D-3","Answered"]],"gtc":"minmax(0,2fr) 100px 120px","minW":600}],"decision":null,"access":[{"l":"Send to owner as question","k":"primary"},{"l":"Open case","h":"P2-S05e-Case.dc.html"}],"equiv":{"Owner":{"h":"P2-O07-Brief.dc.html","same":false,"t":"O-07 Daily Executive Brief"},"Core Group":{"h":"P2-G10-Briefing.dc.html","same":false,"t":"G-10 Briefing and Inquiry Pack"},"Entity":{"h":"P2-S13-Ask.dc.html","same":true}},"_h":1580} };
  }
}

return Component;
});
