// MANIFEST03 S5: data/owner-ai-history.json → js/data/owner-ai-history.js (DCTHistory), read by resolve.js for ask blocks
// that name a history ("hist": "brief"). Usage: node tools/build_ai_history.js
const fs = require("fs"), path = require("path"), root = path.join(__dirname, "..") + "/";
const d = JSON.parse(fs.readFileSync(root + "data/owner-ai-history.json", "utf8")); delete d._note;
fs.writeFileSync(root + "js/data/owner-ai-history.js", "/* Generated by tools/build_ai_history.js from data/owner-ai-history.json. Do not edit by hand. */\nvar DCTHistory = " + JSON.stringify(d) + ";\nif (typeof module !== \"undefined\" && module.exports) module.exports = DCTHistory;\n");
console.log("history:", Object.keys(d).map((k) => k + " " + d[k].length).join(", "));
